name: nopcommerce-practise-workflow

on: 
  push:
     branches:
          - main
          - feature
  pull_request:
     branches: 
          - feature
  schedule:
    - cron: "28 12 * * *"   #runs at 12:28                   
permissions:
  contents: read

jobs:
   job1:
      runs-on: ubuntu-24.04
      steps:
         - name: copy the code 
           uses: actions/checkout@v4
         
         - name: setup dotnet environment
           uses: actions/setup-dotnet@v5
           with:
              dotnet-version: 10.0

         - name: download dependencies
           run: dotnet restore ./src/NopCommerce.sln
        
         - name: compile code
           run: dotnet build ./src/NopCommerce.sln  && echo "Pipeline successfull"
                               
         - name: test the project
           run: dotnet test ./src/NopCommerce.sln   

         - name: download artifact
           uses: actions/upload-artifact@v4
           with:
            name: initiall-artifact 
            path: ./src/Tests/Nop.tests

   


        
         
    
          

      
  